import type { Plan, Category } from "./types";

export const CATEGORIES: { key: Category; label: string; icon: string; blurb: string }[] = [
  { key: "Health", label: "Health", icon: "HeartPulse", blurb: "Cashless hospitalization at 12,000+ network hospitals" },
  { key: "Life", label: "Life", icon: "ShieldCheck", blurb: "Secure your family's future with high-cover term plans" },
  { key: "Motor", label: "Motor", icon: "Car", blurb: "Comprehensive car & bike cover with instant claims" },
  { key: "Travel", label: "Travel", icon: "Plane", blurb: "Worldwide protection for trips, baggage & medical" },
  { key: "Home", label: "Home", icon: "Home", blurb: "Protect your home & belongings against any calamity" },
];

export const PLANS: Plan[] = [
  {
    id: "health-elite",
    name: "Health Shield Elite",
    category: "Health",
    tagline: "Comprehensive family floater with zero room rent capping",
    coverage: 10000000,
    premium: 1499,
    duration: "1 Year",
    popular: true,
    benefits: [
      "Cashless treatment at 12,000+ hospitals",
      "No room-rent capping",
      "Pre & post hospitalization up to 90 days",
      "Annual free health check-up",
      "Restore benefit — 100% sum insured refilled",
    ],
    features: [
      { label: "Claim Settlement", value: "99.2%" },
      { label: "Network Hospitals", value: "12,000+" },
      { label: "Waiting Period", value: "30 days" },
      { label: "No Claim Bonus", value: "Up to 100%" },
    ],
    eligibility: ["Age 18–65 years", "Indian resident", "Medical check-up above 45 yrs"],
    documentsRequired: ["Aadhaar / PAN", "Address proof", "Passport-size photo", "Medical reports (if applicable)"],
    terms: [
      "30-day initial waiting period for illnesses.",
      "Pre-existing diseases covered after 36 months.",
      "Free-look period of 15 days from policy issuance.",
    ],
  },
  {
    id: "health-super",
    name: "Super Care Health",
    category: "Health",
    tagline: "Affordable individual cover with wellness rewards",
    coverage: 3000000,
    premium: 749,
    duration: "1 Year",
    benefits: [
      "Cashless network hospitals",
      "Daycare procedures covered",
      "Wellness reward points",
      "Tax benefits under 80D",
    ],
    features: [
      { label: "Claim Settlement", value: "98.4%" },
      { label: "Network Hospitals", value: "9,500+" },
      { label: "Waiting Period", value: "30 days" },
      { label: "No Claim Bonus", value: "Up to 50%" },
    ],
    eligibility: ["Age 18–60 years", "Indian resident"],
    documentsRequired: ["Aadhaar / PAN", "Address proof", "Passport-size photo"],
    terms: ["30-day initial waiting period.", "Free-look period of 15 days."],
  },
  {
    id: "life-secure",
    name: "Life Secure Term Plan",
    category: "Life",
    tagline: "High cover term insurance up to ₹2 Cr at low premiums",
    coverage: 20000000,
    premium: 999,
    duration: "40 Years",
    popular: true,
    benefits: [
      "Life cover up to ₹2 Crore",
      "Terminal illness benefit",
      "Optional accidental death rider",
      "Premium waiver on disability",
      "Tax benefits under 80C & 10(10D)",
    ],
    features: [
      { label: "Claim Settlement", value: "99.5%" },
      { label: "Max Cover", value: "₹2 Cr" },
      { label: "Policy Term", value: "Up to 40 yrs" },
      { label: "Entry Age", value: "18–65" },
    ],
    eligibility: ["Age 18–65 years", "Annual income proof", "Non-tobacco preferred rates"],
    documentsRequired: ["Aadhaar / PAN", "Income proof", "Medical questionnaire", "Bank details"],
    terms: [
      "Suicide clause: no payout within first 12 months.",
      "Premiums payable throughout the policy term.",
      "Free-look period of 30 days.",
    ],
  },
  {
    id: "life-invest",
    name: "Wealth Plus ULIP",
    category: "Life",
    tagline: "Life cover plus market-linked wealth creation",
    coverage: 5000000,
    premium: 2500,
    duration: "20 Years",
    benefits: [
      "Life cover + investment growth",
      "Choice of 8 fund options",
      "Free fund switches",
      "Loyalty additions",
    ],
    features: [
      { label: "Fund Options", value: "8" },
      { label: "Lock-in", value: "5 yrs" },
      { label: "Policy Term", value: "10–25 yrs" },
      { label: "Entry Age", value: "18–60" },
    ],
    eligibility: ["Age 18–60 years", "Income proof"],
    documentsRequired: ["Aadhaar / PAN", "Income proof", "Bank details"],
    terms: ["Market risks apply.", "5-year lock-in period.", "Free-look period of 30 days."],
  },
  {
    id: "motor-comprehensive",
    name: "Motor Secure Comprehensive",
    category: "Motor",
    tagline: "Own-damage + third-party cover with zero-depreciation",
    coverage: 1500000,
    premium: 583,
    duration: "1 Year",
    popular: true,
    benefits: [
      "Zero depreciation cover",
      "24x7 roadside assistance",
      "Cashless repairs at 5,000+ garages",
      "Engine & gearbox protection",
      "No claim bonus up to 50%",
    ],
    features: [
      { label: "Claim Settlement", value: "98.9%" },
      { label: "Network Garages", value: "5,000+" },
      { label: "IDV", value: "Customisable" },
      { label: "Add-ons", value: "10+" },
    ],
    eligibility: ["Valid vehicle registration (RC)", "Valid driving licence"],
    documentsRequired: ["RC copy", "Previous policy", "Driving licence", "Vehicle photos"],
    terms: ["Depreciation applies without add-on.", "Claims subject to survey.", "Free-look not applicable on motor."],
  },
  {
    id: "motor-tp",
    name: "Motor Third-Party Saver",
    category: "Motor",
    tagline: "Mandatory third-party liability at the best price",
    coverage: 750000,
    premium: 210,
    duration: "1 Year",
    benefits: [
      "Legal third-party liability cover",
      "Personal accident cover for owner-driver",
      "Instant policy issuance",
    ],
    features: [
      { label: "Issuance", value: "Instant" },
      { label: "PA Cover", value: "₹15 L" },
      { label: "Validity", value: "1 year" },
      { label: "Renewal", value: "Online" },
    ],
    eligibility: ["Valid vehicle registration (RC)"],
    documentsRequired: ["RC copy", "Driving licence"],
    terms: ["Covers third-party liability only.", "No own-damage cover."],
  },
  {
    id: "travel-global",
    name: "Global Travel Protect",
    category: "Travel",
    tagline: "Worldwide cover for medical, baggage & trip delays",
    coverage: 4000000,
    premium: 349,
    duration: "Per Trip",
    benefits: [
      "Emergency medical cover worldwide",
      "Baggage loss & delay compensation",
      "Trip cancellation cover",
      "24x7 global assistance",
      "Passport loss assistance",
    ],
    features: [
      { label: "Coverage", value: "Worldwide" },
      { label: "Medical", value: "$50,000" },
      { label: "Assistance", value: "24x7" },
      { label: "Issuance", value: "Instant" },
    ],
    eligibility: ["Valid passport", "Age 1–70 years"],
    documentsRequired: ["Passport copy", "Travel itinerary", "Visa (if applicable)"],
    terms: ["Pre-existing conditions excluded.", "Cover valid for declared trip dates only."],
  },
  {
    id: "travel-student",
    name: "Student Travel Guard",
    category: "Travel",
    tagline: "Tailored cover for students studying abroad",
    coverage: 6000000,
    premium: 899,
    duration: "1 Year",
    benefits: [
      "Medical & dental cover",
      "Study interruption benefit",
      "Sponsor protection",
      "Mental wellness support",
    ],
    features: [
      { label: "Coverage", value: "Worldwide" },
      { label: "Term", value: "Up to 2 yrs" },
      { label: "Medical", value: "$100,000" },
      { label: "Sublimits", value: "Low" },
    ],
    eligibility: ["Enrolled student", "Age 16–35 years"],
    documentsRequired: ["Passport", "University admission letter", "Visa"],
    terms: ["Cover during enrolment period.", "Adventure sports excluded."],
  },
  {
    id: "home-shield",
    name: "Home Shield Plus",
    category: "Home",
    tagline: "Structure + contents cover against fire, theft & calamity",
    coverage: 8000000,
    premium: 416,
    duration: "1 Year",
    popular: true,
    benefits: [
      "Building structure cover",
      "Contents & valuables cover",
      "Fire, flood & earthquake protection",
      "Burglary & theft cover",
      "Alternate accommodation costs",
    ],
    features: [
      { label: "Perils Covered", value: "15+" },
      { label: "Claim Settlement", value: "97.8%" },
      { label: "Term", value: "1–10 yrs" },
      { label: "Add-ons", value: "Jewellery, Electronics" },
    ],
    eligibility: ["Home owner or tenant", "Valid ownership / rental proof"],
    documentsRequired: ["Ownership / rental agreement", "Address proof", "Valuation of contents"],
    terms: ["Wear & tear excluded.", "Valuables above sub-limit need declaration."],
  },
  {
    id: "home-content",
    name: "Contents Care",
    category: "Home",
    tagline: "Lightweight cover for renters' belongings",
    coverage: 1500000,
    premium: 149,
    duration: "1 Year",
    benefits: [
      "Household contents cover",
      "Portable electronics cover",
      "Theft & burglary",
    ],
    features: [
      { label: "Perils Covered", value: "8+" },
      { label: "Term", value: "1 yr" },
      { label: "Issuance", value: "Instant" },
      { label: "Ideal for", value: "Renters" },
    ],
    eligibility: ["Tenant with rental proof"],
    documentsRequired: ["Rental agreement", "Address proof"],
    terms: ["Structure not covered.", "Sub-limits apply on electronics."],
  },
];

export function getPlan(id: string): Plan | undefined {
  return PLANS.find((p) => p.id === id);
}
