"use client";

import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/lib/utils";
import type { Plan } from "@/lib/types";

export function DownloadBrochure({ plan }: { plan: Plan }) {
  const handleDownload = () => {
    const lines = [
      "INSUREPLUS — PLAN BROCHURE",
      "==================================",
      "",
      `Plan Name:      ${plan.name}`,
      `Category:       ${plan.category}`,
      `Coverage up to: ${formatCurrency(plan.coverage)}`,
      `Premium from:   ${formatCurrency(plan.premium)}/month`,
      `Duration:       ${plan.duration}`,
      "",
      "KEY BENEFITS",
      "----------------------------------",
      ...plan.benefits.map((b) => `  • ${b}`),
      "",
      "ELIGIBILITY",
      "----------------------------------",
      ...plan.eligibility.map((e) => `  • ${e}`),
      "",
      "DOCUMENTS REQUIRED",
      "----------------------------------",
      ...plan.documentsRequired.map((d) => `  • ${d}`),
      "",
      "TERMS & CONDITIONS",
      "----------------------------------",
      ...plan.terms.map((t) => `  • ${t}`),
      "",
      "This is an illustrative brochure generated by the InsurePlus demo platform.",
      "IRDAI Reg. No. 000 · care@insureplus.com · 1800-123-4567",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${plan.id}-brochure.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Button variant="outline" className="w-full" onClick={handleDownload}>
      <Download className="h-4 w-4" /> Download Brochure
    </Button>
  );
}
